Repository TencentBlueKing/bk-training-award-open, pull requests merged in 2022-02, with the labels that each got.

#60 bugfix: 文件上传problem(#59)
  awards_apply/utils/upload_file_handler.py
Labels: bug

#74 bugfix: 修复上传文件返回路径错误 (#73)
  awards_apply/utils/upload_file_handler.py
  awards_apply/views/file_handle.py
Labels: bugfix

#76 feature: 组管理添加分页, 规范文件命名(#75)
  awards_apply/serializers/__init__.py
  awards_apply/serializers/secretary_serializer.py
  awards_apply/utils/pagination.py
  awards_apply/views/secretary.py
Labels: feature

#92 bugfix: 修正数据库迁移文件(#91)
  awards_apply/migrations/0001_initial.py
  awards_apply/migrations/0002_auto_20220119_2247.py
  awards_apply/migrations/0003_auto_20220120_1320.py
  awards_apply/migrations/0004_auto_20220120_1417.py
  awards_apply/migrations/0005_auto_20220127_2311.py
  awards_apply/migrations/0006_awardapplicationrecord_approval_turn.py
  awards_apply/migrations/0007_auto_20220218_1708.py
Labels: bug

#94 bugfix: 修复管理员表无初始化数据(#93)
  awards_apply/admin.py
  awards_apply/migrations/0002_auto_20220221_2159.py
Labels: bug

#104 bugfix: 完善空值校验 #99
  frontend/desktop/.babelrc
  frontend/desktop/package.json
  frontend/desktop/src/components/select-search/index.vue
  frontend/desktop/src/views/award-manager/award-form/index.vue
  frontend/desktop/src/views/award-manager/index.vue
  frontend/desktop/src/views/canawards/index.vue
  frontend/desktop/src/views/checkpage/index.vue
  frontend/desktop/src/views/group-manager/components/DialogArea/GroupDialog/index.vue
  frontend/desktop/src/views/group-manager/index.vue
Labels: bugfix

#109 feature: 新增了我的申请、编辑奖项、删除奖项接口
  awards_apply/serializers/award_serializers.py
  awards_apply/utils/const.py
  awards_apply/utils/exception.py
  awards_apply/utils/middlerwares.py
  awards_apply/utils/user_info.py
  awards_apply/views/award_view.py
Labels: feature

#111 feature: 获取秘书可管理组接口, userinfo注入is_admin,is_secretary字段(#110)
  awards_apply/urls.py
  awards_apply/views/secretary.py
  awards_apply/views/user.py
Labels: feature

#119 bugfix: 修复用户不是秘书时调用secretary_department接口报错, 对秘书列表进行数据校验(#118)
  awards_apply/serializers/secretary_serializer.py
  awards_apply/utils/json_schema_validator.py
  awards_apply/views/secretary.py
  requirements.txt
Labels: bugfix
