Repository TencentBlueKing/bk-training-award-open, pull requests merged in 2022-03, with the labels that each got.

#121 bugfix: 审批与不通过审批操作后审批状态错误,修复创建申请时未写入审批人,etc.(#120)
  awards_apply/serializers/application_serializer.py
  awards_apply/serializers/award_serializers.py
  awards_apply/views/secretary.py
Labels: bugfix, Optimize

#129 bugfix: 可申请奖项和历史获得奖项排序问题
  awards_apply/views/award_view.py
Labels: bugfix

#126 bugfix: 修复上传文件路径错误(#125)
  awards_apply/migrations/0003_auto_20220305_2112.py
  awards_apply/models.py
  awards_apply/serializers/application_serializer.py
  awards_apply/serializers/award_serializers.py
  awards_apply/utils/upload_file_handler.py
Labels: bugfix

#134 bugfix: 组织秘书展示与秘书字段校验(#128)
  awards_apply/serializers/secretary_serializer.py
  awards_apply/utils/permission.py
  awards_apply/views/secretary.py
Labels: bugfix

#136 bugfix: 修复了审核失败后无法重新申请奖项的问题
  awards_apply/serializers/award_serializers.py
  awards_apply/views/award_view.py
Labels: bugfix

#143 initial commit: 增加了基础的框架代码
  .dockerignore
  .github/workflows/python-ci.yaml
  .gitignore
  .pre-commit-config.yaml
  Dockerfile
  LICENSE
  Makefile
  docs/contributing.md
  docs/dev_guide.md
  docs/specification/commit.md
  docs/specification/review.md
  readme.md
  readme_en.md
  src/api/bin/start.sh
  src/api/bin/start_dev.sh
  src/api/bk_award/__init__.py
  src/api/bk_award/asgi.py
  src/api/bk_award/settings/__init__.py
  src/api/bk_award/settings/django.py
  src/api/bk_award/settings/overlays/__init__.py
  src/api/bk_award/settings/overlays/prod.py
  src/api/bk_award/urls.py
  src/api/bk_award/wsgi.py
  src/api/manage.py
  src/api/poetry.lock
  src/api/pyproject.toml
Labels: nextGen
